image: canopytax/alpine

services:
  - canopytax/postgresdb

before_script:
  - echo "hello world"
  - python3 -m pip install -r requirements.txt

test:
  script:
    - echo "doing some tests"
    - echo $(( RANDOM % 100 ))% 

deploy:
  script:
    - echo "failed deploy"
    - exit 1
