name: toggle-meister
labels:
  stack: python
  squad: black

expose: True
healthcheck_url: /heartbeat
port: 8445

worker_commmand: ['tini', './cron.sh']

environment:
  default:
    GOOGLE_ORG: canopytax.com
    DATABASE_MAX_POOL_SIZE: 12
    DATABASE_DB_NAME: tmeisterdb
    DATABASE_USER: tmeister_app
    SKIP_MIGRATIONS: true
  stage:
    ENV_LOCATION: stage
    COOKIE_NAME: canopytogglemeister
  production:
    COOKIE_NAME: canopytoggles
    ENV_LOCATION: Prod
    SLACK_CHANNEL: '#dev-camp'
    SLACK_REMINDER_TIME: '15:15'
    SLACK_REMINDER_DAY: 'wednesday'

secrets:
  tmeister:
    DATABASE_URL: database_hostname
    DATABASE_PASS: database_password
    GOOGLE_ID: google_id
    GOOGLE_SECRET: google_secret
    COOKIE_KEY: cookie_key
    SENTRY_URL: sentry_dsn
    SLACK_WEBHOOK_URL: slack_webhook_url


migration:
#  command: ["alembic", "upgrade", "head"]
  command: ["sleep", "1000"]
  environment:
    default:
      DATABASE_MIGRATION_USER: tmeister_sa
  secrets:
    tmeister:
      DATABASE_URL: database_hostname
      DATABASE_MIGRATION_PASS: database_migration_password
