version: '2'
services:
  postgres:
    image: canopytax/postgresdb
    ports:
      - 5432:5432
  
  tmeister:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app/
    environment:
      DATABASE_URL: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_DB_NAME: postgres
      DEBUG: "true"
      AIOHTTP_NOSENDFILE: "true"
      IS_LOCAL: "true"
    links:
      - postgres
    ports:
      - 8445:8445
