name: 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: build docker
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          CI_COMMIT_SHA: ${{ github.sha }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build --pull -t "canopytax/toggle-meister:$CI_COMMIT_SHA" .
        docker push canopytax/toggle-meister:$CI_COMMIT_SHA
